tests/test_basic: Fix to work with newer versions of pytest
Fix an error with newer versions of pytest (9.1.0) by converting the
generator into a tuple to resolve:

E   pytest.PytestRemovedIn10Warning: Passing a non-Collection iterable to parametrize is deprecated.
E   Test: tests/test_basic.py::test_boolean_conversion, argvalues type: chain
E   Please convert to a list or tuple.
E   See https://docs.pytest.org/en/stable/deprecations.html#parametrize-iterators
ERROR: tests/test_basic.py:tests/test_basic.py